INSERT INTO users (name, age) VALUES ('Mike', 34);
INSERT INTO users (name, age) VALUES ('Oliver', 22);
INSERT INTO users (name, age) VALUES ('Mark', 52);
INSERT INTO users (name, age) VALUES ('Nick', 74);
INSERT INTO users (name, age) VALUES ('Jason', 23);
INSERT INTO users (name, age) VALUES ('David', 13);
INSERT INTO users (name, age) VALUES ('Omar', 77);
INSERT INTO users (name, age) VALUES ('Maddy', 43);
INSERT INTO users (name, age) VALUES ('Sarah', 76);
INSERT INTO users (name, age) VALUES ('Joe', 34);
INSERT INTO users (name, age) VALUES ('Biden', 85);
INSERT INTO users (name, age) VALUES ('Tati', 11);
INSERT INTO users (name, age) VALUES ('Jacob', 2);
INSERT INTO users (name, age) VALUES ('Jenny', 38);
INSERT INTO users (name, age) VALUES ('Brain', 30);
INSERT INTO users (name, age) VALUES ('Homer', 34);
INSERT INTO users (name, age) VALUES ('Marge', 23);
INSERT INTO users (name, age) VALUES ('Lisa', 73);
INSERT INTO users (name, age) VALUES ('Bart', 39);
INSERT INTO users (name, age) VALUES ('Mel', 20);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('coffee','drink',528765,'11/5/2019','10/4/2021' );
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('snowboarding','sports',857992,'6/28/2019','11/16/2021' );
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('golf','sports',380725,'11/27/2019','4/22/2021' );
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('racing','sports',108288,'3/2/2019','10/19/2021' );
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('toy car','toys',606829,'7/26/2019','7/4/2021' );
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('sailing','sports',489337,'8/10/2019','6/8/2021' );
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('helicopter','toys',283373,'11/13/2019','11/1/2021' );
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('legos','toys',682260,'6/10/2019','8/17/2021' );
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('website','tech',228592,'10/8/2019','11/2/2021' );
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('tech','tech',600880,'10/12/2019','6/19/2021' );

INSERT INTO pledges (amount, user_id, project_id) VALUES (2628, 15, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (232, 9, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3595, 9, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (310, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (678, 16, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2933, 14, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4607, 13, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2735, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3935, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2986, 18, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3545, 4, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1718, 15, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1884, 6, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3441, 10, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3379, 16, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (65, 12, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3637, 4, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4511, 20, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (884, 20, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2829, 3, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (690, 18, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3946, 4, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3729, 12, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (519, 14, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1725, 20, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3906, 11, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2195, 16, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2389, 16, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2405, 10, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1385, 15, 7);